### ISSUE TITLE
[Request] Discord Notifier - Customize Ping

### ISSUE THREAD

**Issue by rg9400** [crazy-max/diun#188]
Right now, the discord notifier seems to ping `@here`, which is less than ideal because it either pings everyone in a channel, or you can suppress that so that it pings no one. There are ways to mitigate this issue such as creating a specific channel where only one user would get the `@here` ping, but that seems less than ideal.

Suggestion: Allow the input of a specific user's discord ID to override who gets pinged. Also give an option to not ping at all in case the user wants to throw the notifications into a notification channel.

EDIT: I also think it is worth noting that there does not seem to be anyway to disable a webhook from using things like `@here` or `@everyone`, so even throwing them into their own channel does not seem to work.

**Comment by crazy-max** [comment]
@rg9400 LGTM I will make some improvements and keep you in touch.

**Comment by crazy-max** [comment]
@rg9400 I've pushed some changes with a [`mention` setting](https://github.com/crazy-max/diun/blob/b57d49dae287daec05d3793646747f411921ce30/internal/config/fixtures/config.test.yml#L18) for the discord notifier. CAn you try the `crazymax/diun:edge` image and let me know?

**Comment by rg9400** [comment]
I noticed a few things

1. It seems to still ping `@here`, even if you set another ID. It just pings both
![image](https://user-images.githubusercontent.com/39887349/95391160-2f937980-08bc-11eb-9757-59acd1b0f87f.png)

2. The user pings in Discord follow the format `<@!id>`, so `@id` doesn't actually ping anyone. 

3. Not sure if there's a way to not mention anyone at all. Does leaving it blank do that? Right now, because `@here` is being appended each time, it is hard to check.

**Comment by crazy-max** [comment]
Can you pull the `edge` tag again?

**Comment by rg9400** [comment]
The `@here` is now gone, but the `@id` still doesn't trigger the ping because of the format Discord is expecting which is `<@!id>`...unless there's a specific format for the user ID within the settings?

I am waiting for an upstream image update to test if doing `mention: ` will prevent all pings.

**Comment by crazy-max** [comment]
@rg9400 

> but the @id still doesn't trigger the ping because of the format Discord is expecting

Yes you're right I will add a new impl for that.

> I am waiting for an upstream image update to test if doing mention: will prevent all pings.

If you remove `mention: ` property no one should be mentioned (`Image update for docker.io/...`).

**Comment by rg9400** [comment]
Thanks! I tested the lack of the `mention:` property, and it is working as intended (no one gets pinged)

**Comment by crazy-max** [comment]
@rg9400 I have updated tje `edge` tag. You can now mention a list of users or roles:

```yaml
notif:
  discord:
    webhookURL: https://discordapp.com/api/webhooks/1234567890/Abcd-eFgh-iJklmNo_pqr
    mentions:
      - "@here"
      - "@everyone"
      - "<@124>"
      - "<@125>"
      - "<@&200>"
    timeout: 10s
```

**Comment by rg9400** [comment]
Thanks for the quick help! It is working as intended per my initial testing

**Comment by crazy-max** [comment]
@rg9400 Will be available on next release
